# =====================================================
# APPLICATION CONFIGURATION "AI VOICE ASSISTANT"
# =====================================================

# Main application settings
app:
  name: "AI Voice Assistant"
  version: "1.0.0"
  debug: false
  
# Audio settings
audio:
  sample_rate: 48000
  channels: 1
  chunk_size: 1024
  format: "int16"
  
# STT settings (Speech Recognition)
stt:
  sample_rate: 16000
  chunk_size: 1024
  energy_threshold: 100
  dynamic_energy_threshold: true
  pause_threshold: 0.5
  phrase_threshold: 0.3
  non_speaking_duration: 0.3
  
# Screen capture settings
screen_capture:
  quality: 85
  format: "webp"
  max_width: 1920
  max_height: 1080
  
# gRPC client settings
grpc:
  server_host: "YOUR_EXTERNAL_SERVER_IP"  # TODO: Replace with actual external server IP
  server_port: 50051
  timeout: 30
  retry_attempts: 3
  retry_delay: 1
  
# Logging settings
logging:
  level: "INFO"
  file: "~/Library/Logs/Nexy/app.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Accessibility settings
accessibility:
  voice_feedback: true
  sound_notifications: true
  startup_sound: true
  error_sound: true
  success_sound: true
  
# Autostart settings
autostart:
  enabled: false
  delay: 5  # Delay in seconds after system login
  
# Performance settings
performance:
  max_memory: "512MB"
  cpu_limit: 0.8  # Maximum CPU load
  battery_optimization: true
  
# Security settings
security:
  require_network_permission: true
  require_microphone_permission: true
  require_screen_permission: true


