accessibility:
  error_sound: true
  sound_notifications: true
  startup_sound: true
  success_sound: true
  voice_feedback: true
app:
  bundle_id: com.nexy.assistant
  debug: false
  name: Nexy
  team_id: 5NKLL2CLB9
  version: 1.71.0
audio:
  bluetooth_policy: auto
  channels: 1
  chunk_size: 1024
  device_manager:
    auto_switch_to_best: true
    auto_switch_to_headphones: true
    cache_timeout: 5.0
    device_priorities:
      airpods: 100
      beats: 95
      bluetooth_headphones: 90
      bluetooth_speakers: 70
      built_in: 20
      microphone: 5
      other: 10
      system_speakers: 40
      usb_audio: 60
      usb_headphones: 85
      virtual_device: 1
    enabled: true
    exclude_virtual_devices: true
    monitoring_interval: 3.0
    switch_cooldown: 2.0
    virtual_device_keywords:
    - blackhole
    - soundflower
    - loopback
    - virtual
    - aggregate
    - multi-output
    - sound source
    - audio hijack
  follow_system_default: false
  format: int16
  preflush_on_switch: false
  retries: 2
  sample_rate: 48000
  settle_ms: 100
  use_coreaudio_listeners: true
autostart:
  delay: 5
  enabled: false
grpc:
  auto_fallback: true
  config_file: config/unified_config.yaml
  connection_check_interval: 5
  server_priority:
  - local
  - production
  - fallback
logging:
  backup_count: 5
  error_file: ~/Library/Logs/Nexy/errors.log
  file: ~/Library/Logs/Nexy/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  loggers:
    accessibility: nexy.accessibility
    audio: nexy.audio
    grpc: nexy.grpc
    main: Nexy
    screen_capture: nexy.screen_capture
    stt: nexy.stt
  max_size: 10MB
performance:
  battery_optimization: true
  cpu_limit: 0.8
  max_memory: 512MB
screen_capture:
  format: webp
  max_height: 1080
  max_width: 1920
  quality: 85
security:
  require_microphone_permission: true
  require_network_permission: true
  require_screen_permission: true
stt:
  chunk_size: 1024
  dynamic_energy_threshold: true
  energy_threshold: 100
  non_speaking_duration: 0.3
  pause_threshold: 0.5
  phrase_threshold: 0.3
  sample_rate: 16000
update_manager:
  announce_updates: false
  appcast_url: https://api.nexy.ai/updates/appcast.xml
  auto_install: false
  check_interval: 24
  check_on_startup: false
  check_time: 02:00
  enabled: false
  log_updates: true
  retry_attempts: 3
  retry_delay: 300
  silent_mode: true
