# =====================================================
# КОНФИГУРАЦИЯ ЛОГИРОВАНИЯ ДЛЯ macOS ПРИЛОЖЕНИЯ
# =====================================================

version: 1
disable_existing_loggers: false

# Форматы логов
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  simple:
    format: "%(levelname)s - %(message)s"

# Обработчики логов
handlers:
  # Файл логов
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: "~/Library/Logs/VoiceAssistant/app.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
    
  # Консоль (для отладки)
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
    
  # Системный журнал macOS
  system_handler:
    class: logging.handlers.SysLogHandler
    level: WARNING
    formatter: simple
    address: "/var/run/syslog"
    
  # Ошибки в отдельный файл
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: "~/Library/Logs/VoiceAssistant/errors.log"
    maxBytes: 5242880  # 5MB
    backupCount: 3
    encoding: utf8

# Логгеры
loggers:
  # Основной логгер приложения
  VoiceAssistant:
    level: INFO
    handlers: [file_handler, console_handler, error_file_handler]
    propagate: false
    
  # Логгер для аудио
  audio:
    level: INFO
    handlers: [file_handler]
    propagate: false
    
  # Логгер для STT
  stt:
    level: INFO
    handlers: [file_handler]
    propagate: false
    
  # Логгер для gRPC
  grpc:
    level: INFO
    handlers: [file_handler]
    propagate: false
    
  # Логгер для захвата экрана
  screen_capture:
    level: INFO
    handlers: [file_handler]
    propagate: false
    
  # Логгер для доступности
  accessibility:
    level: INFO
    handlers: [file_handler, console_handler]
    propagate: false

# Корневой логгер
root:
  level: WARNING
  handlers: [system_handler]


