accessibility:
  error_sound: true
  sound_notifications: true
  startup_sound: true
  success_sound: true
  voice_feedback: true
app:
  bundle_id: com.nexy.assistant
  debug: false
  name: Nexy
  team_id: 5NKLL2CLB9
  version: 1.71.0
audio:
  bluetooth_policy: auto
  channels: 1
  chunk_size: 1024
  device_manager:
    auto_switch_to_best: true
    auto_switch_to_headphones: true
    cache_timeout: 5.0
    device_priorities:
      airpods: 100
      beats: 95
      bluetooth_headphones: 90
      bluetooth_speakers: 70
      built_in: 20
      microphone: 5
      other: 10
      system_speakers: 40
      usb_audio: 60
      usb_headphones: 85
      virtual_device: 1
    enabled: true
    exclude_virtual_devices: true
    monitoring_interval: 3.0
    switch_cooldown: 2.0
    virtual_device_keywords:
    - blackhole
    - soundflower
    - loopback
    - virtual
    - aggregate
    - multi-output
    - sound source
    - audio hijack
  follow_system_default: false
  format: int16
  preflush_on_switch: false
  retries: 2
  sample_rate: 48000
  settle_ms: 100
  use_coreaudio_listeners: true
autostart:
  delay: 5
  enabled: false
logging:
  backup_count: 5
  error_file: ~/Library/Logs/Nexy/errors.log
  file: ~/Library/Logs/Nexy/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: DEBUG
  loggers:
    accessibility: nexy.accessibility
    audio: nexy.audio
    grpc: nexy.grpc
    main: Nexy
    screen_capture: nexy.screen_capture
    stt: nexy.stt
  max_size: 10MB
network:
  appcast:
    base_url: https://api.nexy.ai/updates
    check_interval: 24
    timeout: 30
  auto_fallback: true
  connection_check_interval: 5
  grpc_servers:
    fallback:
      host: backup.nexy.ai
      port: 443
      retry_attempts: 2
      retry_delay: 2.0
      ssl: true
      timeout: 90
    local:
      host: 127.0.0.1
      port: 50051
      retry_attempts: 2
      retry_delay: 0.5
      ssl: false
      timeout: 60
    production:
      host: 20.151.51.172
      port: 50051
      retry_attempts: 3
      retry_delay: 1.0
      ssl: false
      timeout: 120
  ping_hosts:
  - 8.8.8.8
  - 1.1.1.1
  - google.com
  ping_timeout: 5
performance:
  battery_optimization: true
  cpu_limit: 0.8
  max_memory: 512MB
screen_capture:
  format: webp
  max_height: 1080
  max_width: 1920
  quality: 85
security:
  require_microphone_permission: true
  require_network_permission: true
  require_screen_permission: true
stt:
  chunk_size: 1024
  dynamic_energy_threshold: true
  energy_threshold: 100
  non_speaking_duration: 0.3
  pause_threshold: 0.5
  phrase_threshold: 0.3
  sample_rate: 16000
update_manager:
  announce_updates: false
  auto_install: false
  check_interval: 24
  check_on_startup: false
  check_time: 02:00
  enabled: false
  log_updates: true
  retry_attempts: 3
  retry_delay: 300
  silent_mode: true

# Конфигурации интеграций
integrations:
  tray_controller:
    icon_size: 16
    show_status_in_menu: true
    enable_notifications: true
    auto_update_status: true
    debug_mode: true
  
  keyboard:
    key_to_monitor: space
    backend: quartz
    short_press_threshold: 0.6
    long_press_threshold: 1.0
    event_cooldown: 0.1
    hold_check_interval: 0.05
    debounce_time: 0.1
  
  input_processing:
    enable_keyboard_monitoring: true
    auto_start: true
  
  permissions:
    check_interval: 30
    auto_request_required: true
    show_instructions: true
    open_preferences: true
    debug_mode: true
  
  network_manager:
    check_interval: 30.0
    ping_timeout: 5.0
    ping_hosts: ["8.8.8.8", "1.1.1.1", "google.com"]
  
  audio_device:
    auto_switch_enabled: true
    monitoring_interval: 3.0
    switch_delay: 0.5
    enable_microphone_on_listening: true
    disable_microphone_on_sleeping: true
    disable_microphone_on_processing: true
  
  voice_recognition:
    simulate: false
    timeout_sec: 10.0
    simulate_success_rate: 0.7
    simulate_min_delay_sec: 1.0
    simulate_max_delay_sec: 3.0
  
  interrupt_management:
    max_concurrent_interrupts: 5
    interrupt_timeout: 10.0
    retry_attempts: 3
    retry_delay: 1.0
    enable_speech_interrupts: true
    enable_recording_interrupts: true
    enable_session_interrupts: true
    enable_full_reset: true
