name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
    paths: [ 'server/**' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "🚀 Deploying to Azure VM..."
          
          # Выполнить обновление
          if az vm run-command invoke \
            --resource-group Nexy \
            --name nexy-regular \
            --command-id RunShellScript \
            --scripts "/home/azureuser/update-server.sh"; then
            echo "✅ Deployment completed successfully!"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi
          
          # Проверить health endpoint
          echo "🏥 Checking health endpoint..."
          if curl -f http://20.151.51.172/health; then
            echo "✅ Health check passed!"
          else
            echo "❌ Health check failed!"
            exit 1
          fi
