name: Test Azure Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Test Azure Connection
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "🔐 Testing Azure authentication..."
          az account show
          
          echo "🔍 Testing VM access..."
          az vm show --resource-group Nexy --name nexy-regular --query "name" -o tsv
          
          echo "🧪 Testing simple command..."
          az vm run-command invoke \
            --resource-group Nexy \
            --name nexy-regular \
            --command-id RunShellScript \
            --scripts "echo 'Azure connection test successful'"
          
          echo "✅ All tests passed!"
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
